version: '3'
services:
  nuxt:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./frontend/.env
    links:
      - "strapi:strapi"
    volumes:
      - certbot-webroot-sozlk.com:/usr/src/app/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
    networks:
      - strapi_some-net
  strapi:
    build: ./backend
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
    networks:
      - some-net
  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-sozlk.com:/webroots/sozlk.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - certbot-webroot-sozlk.com:/webroots/sozlk.com/.well-known
      - certbot-letsencrypt:/etc/letsencrypt
volumes:
  certbot-webroot-sozlk.com:
  certbot-letsencrypt:

networks:
  strapi_some-net:
    external: true