version: "3"
services:
  strapi:
    build: ./backend
    ports:
      - "1337:1337"
    env_file:
      - ./backend/.env
  nuxt:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - "strapi"
    restart: always
    env_file:
      - ./frontend/.env
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - "strapi"
      - "nuxt"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
