version: '3'
services:
  nuxt:
    build: ./frontend
    ports:
      - "80:3000"
    network_mode: bridge
    env_file:
      - ./frontend/.env
    restart: always
  strapi:
    build: ./backend
    ports:
      - "1337:1337"
    network_mode: bridge
    env_file:
      - ./backend/.env